### ISSUE TITLE
add %{ticket.subject} and %{message.poster} to variables available in new message autoresponder

### ISSUE THREAD

**Issue by alpianon** [alpianon/osTicket-1.7-ClientAuth-CCemails#12]

**Comment by greezybacon** [comment]
Is %{ticket.subject} not available in the stock version?!

**Comment by alpianon** [comment]
you're right :)
added %{message.poster} anyway

**Comment by alpianon** [comment]
solved with https://github.com/alpianon/osTicket-1.7-ClientAuth-CCemails/commit/aa6d76b9497263acf98e083521f0f75919b37900
